using System.ComponentModel.DataAnnotations.Schema;

namespace ProcuLink.Core.Entities;

/// <summary>
/// Tracks every remote file that has been successfully ingested via SFTP pull,
/// keyed by (OrgId, RemotePath) to prevent duplicate imports.
/// EF table: <c>imported_sftp_files</c>.
/// </summary>
[Table("imported_sftp_files")]
public class ImportedSftpFile
{
    public Guid Id { get; set; }

    /// <summary>Owning organisation.</summary>
    public Guid OrgId { get; set; }

    /// <summary>Full remote path as returned by the SFTP server (e.g. <c>/incoming/po-001.csv</c>).</summary>
    public string RemotePath { get; set; } = string.Empty;

    /// <summary>SHA-256 hex digest of the downloaded file bytes — used for content-level dedupe.</summary>
    public string FileHash { get; set; } = string.Empty;

    /// <summary>
    /// The order this claim intends to create, pre-generated by the poller and stored atomically
    /// with the claim insert (never a separate backfill step). Semantics used by resume-on-conflict:
    /// <list type="bullet">
    /// <item><description>a real (non-empty) id — the order was, or is being, created under this
    /// primary key; a retry checks <c>purchase_orders</c> by this id to decide SKIP (it exists) vs
    /// RESUME (a transient failure left it un-created);</description></item>
    /// <item><description><see cref="System.Guid.Empty"/> — SKIP unconditionally: a legacy row
    /// migrated before this column existed, or a claim marked terminally failed after a permanent
    /// stub-creation error (bounds a permanently-bad file so it is not retried forever).</description></item>
    /// </list>
    /// </summary>
    public Guid OrderId { get; set; }

    public DateTime ImportedAt { get; set; }
}
