using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using ProcuLink.Api.Services;
using ProcuLink.Core.Entities;
using ProcuLink.Core.Security;
using ProcuLink.Core.Services;
using ProcuLink.Core.Services.Ai;
using ProcuLink.Core.Services.Mapping;
using ProcuLink.Infrastructure;
using ProcuLink.Infrastructure.Services;
using ProcuLink.Transform.Output;
using ProcuLink.Transform.Parsing;
using Xunit;

namespace ProcuLink.Api.Tests.Services;

/// <summary>
/// Launch batch 3 — artifact provenance at transform time. The OutboundArtifact row must record
/// WHICH connection revision the order was pinned to, a digest of the EFFECTIVE config that drove
/// the transform (per-order override JSON, or the <c>fixed:{format}</c> marker), and the SHA-256
/// of the exact generated bytes — and the generated output itself must remain byte-identical
/// (the buffering added for hashing must not change what is uploaded).
/// </summary>
public class TransformProvenanceTests
{
    private static ProcuLinkDbContext NewDb() =>
        new(new DbContextOptionsBuilder<ProcuLinkDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options);

    private static (OrderService Svc, Func<byte[]?> CapturedBytes) Build(ProcuLinkDbContext db)
    {
        byte[]? captured = null;

        var fileStorage = new Mock<IFileStorageService>();
        fileStorage
            .Setup(s => s.UploadAsync(It.IsAny<Stream>(), It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .Callback<Stream, string, string, CancellationToken>((stream, _, _, _) =>
            {
                using var ms = new MemoryStream();
                stream.Position = 0;
                stream.CopyTo(ms);
                captured = ms.ToArray();
            })
            .ReturnsAsync("artifact-key");

        var svc = new OrderService(
            db,
            fileStorage.Object,
            new OrderParserFactory(new IPurchaseOrderParser[] { new CsvOrderParser() }),
            new Mock<IItemMappingService>().Object,
            new OrderExceptionService(db),
            new Mock<IPoMappingService>().Object,
            new Mock<IAiMappingService>().Object,
            new ITransformService[] { new CsvTransformService(), new JsonTransformService() },
            NullLogger<OrderService>.Instance,
            new Mock<IIntegrationTriggerService>().Object,
            new ProcuLink.Infrastructure.Services.Detection.FormatDetectorService());

        return (svc, () => captured);
    }

    private static async Task<(Guid orgId, Guid orderId, Guid pinnedRevisionId)> SeedResolvedOrderAsync(
        ProcuLinkDbContext db)
    {
        var orgId      = Guid.NewGuid();
        var supplierId = Guid.NewGuid();
        var orderId    = Guid.NewGuid();
        var pinnedRev  = Guid.NewGuid();

        db.Suppliers.Add(new Supplier { Id = supplierId, OrgId = orgId, Name = "Prov Supplier", CreatedAt = DateTime.UtcNow });
        db.PurchaseOrders.Add(new PurchaseOrderEntity
        {
            Id         = orderId,
            OrgId      = orgId,
            SupplierId = supplierId,
            PoNumber   = "PO-PROV-1",
            BuyerName  = "Prov Buyer",
            OrderDate  = new DateOnly(2026, 6, 1),
            Currency   = "EUR",
            Status     = "ready",
            CreatedAt  = DateTime.UtcNow,
            UpdatedAt  = DateTime.UtcNow,
            ConnectionRevisionId = pinnedRev, // the ingest-time pin the artifact must inherit
            Lines =
            {
                new PurchaseOrderLineEntity
                {
                    Id = Guid.NewGuid(), OrderId = orderId, LineNumber = 1,
                    BuyerItemCode = "B-1", SupplierItemCode = "SUP-1", Description = "Widget",
                    Quantity = 3m, Unit = "EA", UnitPrice = 10m, NeedsReview = false, Confidence = 1.0f,
                },
            },
        });

        await db.SaveChangesAsync();
        return (orgId, orderId, pinnedRev);
    }

    [Fact]
    public async Task TransformAsync_FixedPath_StampsRevisionPin_FixedMarkerDigest_AndArtifactSha()
    {
        await using var db = NewDb();
        var (orgId, orderId, pinnedRev) = await SeedResolvedOrderAsync(db);
        var (svc, captured) = Build(db);

        var result = await svc.TransformAsync(orgId, orderId, OutputFormat.Csv, CancellationToken.None);

        Assert.True(result.IsSuccess, result.Error);
        var artifact = await db.OutboundArtifacts.SingleAsync(a => a.OrderId == orderId);

        Assert.Equal(pinnedRev, artifact.ConnectionRevisionId);          // pin copied from the order
        Assert.Equal(ProvenanceHash.TrySha256HexUtf8("fixed:csv"),       // fixed-transformer marker
                     artifact.ConfigDigest);
        Assert.Equal(ProvenanceHash.TrySha256Hex(captured()!),           // hash of the EXACT bytes uploaded
                     artifact.ArtifactSha256);
        Assert.NotNull(artifact.ArtifactSha256);
        Assert.Equal(64, artifact.ArtifactSha256!.Length);               // sha-256 hex
    }

    [Fact]
    public async Task TransformAsync_OverridePath_DigestsTheStoredOverrideJson()
    {
        await using var db = NewDb();
        var (orgId, orderId, _) = await SeedResolvedOrderAsync(db);

        var overrideSvc = new OrderMappingOverrideService(db);
        await overrideSvc.UpsertAsync(orgId, orderId, new OrderMappingOverride
        {
            Output = new OutputMappingConfig
            {
                Header = { ["po"] = new OutputFieldRule { OutputPath = "OrderRef", CanonicalField = "PoNumber" } },
                Lines  = { ["code"] = new OutputFieldRule { OutputPath = "ItemCode", CanonicalField = "SupplierItemCode" } },
            },
        }, CancellationToken.None);

        // Expected digest: SHA-256 of the RAW mappingOverride JSON exactly as stored in canonical_json.
        var stored = await db.PurchaseOrders.AsNoTracking().SingleAsync(o => o.Id == orderId);
        var rawOverrideJson = OrderMappingOverrideReader.ReadRawJson(stored.CanonicalJson);
        Assert.NotNull(rawOverrideJson);
        var expectedDigest = ProvenanceHash.TrySha256HexUtf8(rawOverrideJson);

        var (svc, _) = Build(db);
        var result = await svc.TransformAsync(orgId, orderId, OutputFormat.Csv, CancellationToken.None);

        Assert.True(result.IsSuccess, result.Error);
        var artifact = await db.OutboundArtifacts.SingleAsync(a => a.OrderId == orderId);
        Assert.Equal(expectedDigest, artifact.ConfigDigest);
        Assert.NotEqual(ProvenanceHash.TrySha256HexUtf8("fixed:csv"), artifact.ConfigDigest);
    }

    [Fact]
    public async Task TransformAsync_UnpinnedLegacyOrder_LeavesRevisionNull_ButStillHashes()
    {
        await using var db = NewDb();
        var (orgId, orderId, _) = await SeedResolvedOrderAsync(db);
        // Simulate a legacy order created before V1 pinning.
        var order = await db.PurchaseOrders.SingleAsync(o => o.Id == orderId);
        order.ConnectionRevisionId = null;
        await db.SaveChangesAsync();

        var (svc, captured) = Build(db);
        var result = await svc.TransformAsync(orgId, orderId, OutputFormat.Json, CancellationToken.None);

        Assert.True(result.IsSuccess, result.Error);
        var artifact = await db.OutboundArtifacts.SingleAsync(a => a.OrderId == orderId);
        Assert.Null(artifact.ConnectionRevisionId);                       // nullable = legacy-safe
        Assert.Equal(ProvenanceHash.TrySha256Hex(captured()!), artifact.ArtifactSha256);
        Assert.Equal(ProvenanceHash.TrySha256HexUtf8("fixed:json"), artifact.ConfigDigest);
    }

    /// <summary>
    /// Byte-identical guard for the hashing change itself: the bytes UPLOADED after the
    /// buffering refactor are exactly the fixed transformer's output (CSV is timestamp-free).
    /// </summary>
    [Fact]
    public async Task TransformAsync_BufferingForHash_DoesNotChangeUploadedBytes()
    {
        await using var db = NewDb();
        var (orgId, orderId, _) = await SeedResolvedOrderAsync(db);

        var order = await db.PurchaseOrders.AsNoTracking()
            .Include(o => o.Lines)
            .Include(o => o.Supplier)
            .FirstAsync(o => o.Id == orderId && o.OrgId == orgId);
        var fixedResult = await new CsvTransformService().TransformAsync(order, OutputFormat.Csv, CancellationToken.None);
        fixedResult.Content.Position = 0;
        using var ms = new MemoryStream();
        await fixedResult.Content.CopyToAsync(ms);
        var expected = ms.ToArray();

        var (svc, captured) = Build(db);
        var result = await svc.TransformAsync(orgId, orderId, OutputFormat.Csv, CancellationToken.None);

        Assert.True(result.IsSuccess, result.Error);
        Assert.Equal(expected, captured()); // byte-for-byte identical to the fixed transformer
    }
}
