using System.Text;
using System.Xml.Linq;
using ProcuLink.Core.Entities;
using ProcuLink.Core.Services;
using ProcuLink.Core.Services.Mapping;
using ProcuLink.Transform.Output;
using Xunit;

namespace ProcuLink.Transform.Tests.Output;

/// <summary>
/// B12 TASK 3 — the XML emitter renders VALID namespaced/prefixed XML (UBL cbc:/cac:) when nodes carry
/// Namespace/Prefix, hoisting declarations to the root so siblings don't redeclare and the writer never
/// invents p1:/p2: prefixes. Non-namespaced trees stay byte-identical (see the byte-parity oracle).
/// </summary>
public class OutputTemplateEmitterNamespaceTests
{
    private const string ORDER2 = "urn:oasis:names:specification:ubl:schema:xsd:Order-2";
    private const string CBC = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2";
    private const string CAC = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2";
    private static readonly XNamespace Order2Ns = ORDER2;
    private static readonly XNamespace CbcNs = CBC;
    private static readonly XNamespace CacNs = CAC;

    private static PurchaseOrderEntity ResolvedOrder()
    {
        var id = Guid.NewGuid();
        return new PurchaseOrderEntity
        {
            Id = id, OrgId = Guid.NewGuid(), SupplierId = Guid.NewGuid(),
            PoNumber = "PO-1", Currency = "EUR", OrderDate = new DateOnly(2026, 6, 15),
            Lines = { new PurchaseOrderLineEntity { Id = Guid.NewGuid(), OrderId = id, LineNumber = 1,
                SupplierItemCode = "S-1", Quantity = 3m, UnitPrice = 10m, NeedsReview = false } },
        };
    }

    private static OutputFieldRule Canon(string f) => new() { OutputPath = f, CanonicalField = f };

    private static string Emit(OutputNodeTemplate t)
    {
        var r = new OutputTemplateEmitter().Emit(t, ResolvedOrder(), new OrderMappingOverride());
        r.Content.Position = 0;
        using var sr = new StreamReader(r.Content, Encoding.UTF8);
        return sr.ReadToEnd();
    }

    // A minimal but real UBL shape rendered as generic namespaced XML (the emitter produces namespaced
    // XML under Format=Xml; cXML/UBL formats are refused — they need their envelope, see Emit).
    private static OutputNodeTemplate UblTree() => new()
    {
        Format = OutputFormat.Xml,
        Root = new OutputNode
        {
            Name = "Order", NodeType = OutputNodeType.Object, Namespace = ORDER2,
            Children =
            {
                new OutputNode { Name = "ID", NodeType = OutputNodeType.Field, Prefix = "cbc", Namespace = CBC, Rule = Canon("PoNumber") },
                new OutputNode { Name = "OrderLine", NodeType = OutputNodeType.Array, Prefix = "cac", Namespace = CAC, Collection = "lines",
                    Children =
                    {
                        new OutputNode { Name = "LineItem", NodeType = OutputNodeType.Object, Prefix = "cac", Namespace = CAC,
                            Children = { new OutputNode { Name = "Quantity", NodeType = OutputNodeType.Field, Prefix = "cbc", Namespace = CBC, Rule = Canon("Quantity") } } },
                    } },
            },
        },
    };

    [Fact]
    public void PerNode_Prefix_Emits_Bound_Prefix_Not_AutoGenerated()
    {
        var xml = Emit(UblTree());

        Assert.Contains("xmlns:cbc=\"" + CBC + "\"", xml);
        Assert.Contains("xmlns:cac=\"" + CAC + "\"", xml);
        Assert.Contains("<cbc:ID>PO-1</cbc:ID>", xml);
        Assert.Contains("<cbc:Quantity>3</cbc:Quantity>", xml);
        Assert.DoesNotContain("p1:", xml);     // no writer-invented prefixes
        Assert.DoesNotContain("p2:", xml);
        // Prefixes hoisted to the ROOT element (declared once), not on the first cbc child.
        var firstLine = xml.Split('\n')[1];
        Assert.Contains("xmlns:cbc", firstLine);
        Assert.Contains("xmlns:cac", firstLine);
    }

    [Fact]
    public void PerNode_Namespaces_Resolve_Correctly_When_Parsed()
    {
        var doc = XDocument.Parse(Emit(UblTree()));
        Assert.Equal(Order2Ns + "Order", doc.Root!.Name);                 // root default namespace
        Assert.Equal("PO-1", doc.Root.Element(CbcNs + "ID")!.Value);       // cbc:ID in the cbc namespace
        var line = doc.Root.Element(CacNs + "OrderLine")!;                 // cac:OrderLine in the cac namespace
        Assert.Equal("3", line.Element(CacNs + "LineItem")!.Element(CbcNs + "Quantity")!.Value);
    }

    [Fact]
    public void DefaultNamespace_Node_NoPrefix_PutsRootInThatNamespace()
    {
        var t = new OutputNodeTemplate
        {
            Format = OutputFormat.Xml,
            Root = new OutputNode { Name = "Order", NodeType = OutputNodeType.Object, Namespace = ORDER2,
                Children = { new OutputNode { Name = "ID", NodeType = OutputNodeType.Field, Namespace = ORDER2, Rule = Canon("PoNumber") } } },
        };
        var doc = XDocument.Parse(Emit(t));
        Assert.Equal(Order2Ns + "Order", doc.Root!.Name);
        Assert.Equal(Order2Ns + "ID", doc.Root.Elements().First().Name);   // unprefixed child inherits the default ns
        Assert.DoesNotContain("p1:", Emit(t));
    }

    [Fact]
    public void QualifiedAttribute_Uses_PrefixedForm()
    {
        const string XMLNS = "http://www.w3.org/XML/1998/namespace";
        var t = new OutputNodeTemplate
        {
            Format = OutputFormat.Xml,
            Root = new OutputNode { Name = "Order", NodeType = OutputNodeType.Object,
                Children =
                {
                    new OutputNode { Name = "lang", NodeType = OutputNodeType.Attribute, Prefix = "xml", Namespace = XMLNS,
                        Rule = new OutputFieldRule { FixedValue = "en-US" } },
                    new OutputNode { Name = "ID", NodeType = OutputNodeType.Field, Rule = Canon("PoNumber") },
                } },
        };
        var xml = Emit(t);
        Assert.Contains("xml:lang=\"en-US\"", xml);
        var doc = XDocument.Parse(xml);
        Assert.Equal("en-US", doc.Root!.Attribute(XNamespace.Get(XMLNS) + "lang")!.Value);
    }

    [Fact]
    public void MixedMode_RootNamespacesMap_AND_PerNodePrefix_Throws()
    {
        var t = new OutputNodeTemplate
        {
            Format = OutputFormat.Xml,
            Namespaces = new Dictionary<string, string> { ["cbc"] = CBC },
            Root = new OutputNode { Name = "Order", NodeType = OutputNodeType.Object,
                Children = { new OutputNode { Name = "ID", NodeType = OutputNodeType.Field, Prefix = "cbc", Namespace = CBC, Rule = Canon("PoNumber") } } },
        };
        Assert.Throws<ArgumentException>(() => Emit(t));
    }
}
