using Microsoft.EntityFrameworkCore;
using ProcuLink.Core.Catalog;
using ProcuLink.Core.Entities;
using ProcuLink.Core.Services;

namespace ProcuLink.Infrastructure.Services;

/// <summary>
/// EF Core implementation of <see cref="IItemMappingService"/>.
/// All queries are scoped to (orgId, supplierId) — never cross-tenant.
/// Phase 2 uses exact-match resolution only; fuzzy/AI matching is Phase 4.
/// </summary>
public sealed class ItemMappingService : IItemMappingService
{
    private readonly ProcuLinkDbContext _db;

    public ItemMappingService(ProcuLinkDbContext db)
    {
        _db = db;
    }

    /// <summary>
    /// One candidate row, projected so the deterministic tie-break below can run client-side over a
    /// tiny set instead of being expressed as fragile ordering inside the SQL.
    /// </summary>
    private sealed record MappingCandidate(
        Guid Id, string BuyerItemCode, string SupplierItemCode, DateTime UpdatedAt);

    /// <summary>
    /// Picks ONE row when a code matches several (only possible for case-variant rows written before
    /// <see cref="UpsertAsync"/> became case-aware). An exact-case row always wins; otherwise the
    /// most recently updated, with the id as a final tie-break so the answer never depends on the
    /// order the database happened to return. Determinism matters more than which row wins: a
    /// resolver that alternates between two supplier codes ships two different documents for the
    /// same order.
    /// </summary>
    private static MappingCandidate? PickDeterministically(
        IEnumerable<MappingCandidate> candidates, string trimmedRequested)
    {
        var list = candidates.ToList();
        if (list.Count == 0) return null;

        var exact = list.FirstOrDefault(
            c => string.Equals(c.BuyerItemCode, trimmedRequested, StringComparison.Ordinal));
        if (exact is not null) return exact;

        return list
            .OrderByDescending(c => c.UpdatedAt)
            .ThenBy(c => c.Id)
            .First();
    }

    // ── Query-plan note (WP-14) — MEASURED, artefact in docs/ops/ ────────────────
    // The predicates below fold case with `.ToLower()`, which the plain btree index
    // IX(org_id, supplier_id, buyer_item_code) cannot serve on its third column. The planner
    // therefore ABANDONS that index entirely and picks some form of scan.
    //
    // Real EXPLAIN (ANALYZE, BUFFERS) output — regenerated by
    // ItemMappingBatchResolvePerfPostgresTests into docs/ops/wp14-item-mapping-explain.md, so the
    // numbers below can be re-derived rather than taken on trust:
    //
    //   pre-WP-14 (`buyer_item_code = $1`)   Index Scan on IX(org,supplier,code), 3 buffers
    //   WP-14, 250-code supplier             Index Scan on IX(supplier_id) + Filter, 249 rows discarded
    //   WP-14, 5 000-code supplier           SEQ SCAN on item_mappings, 5 249 rows discarded
    //   WP-14, 315k-row table (reported)     Bitmap Heap Scan, ~503 buffers vs 4, ~1.4 ms vs 0.07 ms
    //
    // THREE claims an earlier version of this comment made that are FALSE, all reproduced:
    //   1. "the exact-match term is OR'd in FIRST so the planner keeps the fully-indexed path
    //      available" — writing `lower()` first yields the SAME plan node discarding the SAME rows.
    //      (EXPLAIN's printed `Filter:` echoes the source term order, which is a formatting
    //      artefact and not a different plan — that echo is probably what the belief was built on.)
    //      Pinned by WritingTheOrTermsEitherWayRound_ProducesTheSamePlan.
    //   2. "This is NOT a sequential scan of the table" — it can be, and at moderate table sizes it
    //      IS: the artefact above shows a plain Seq Scan on item_mappings. The planner's choice
    //      depends on table size and statistics; nothing here guarantees it stays indexed.
    //   3. the cost was reported as ~55x buffers; the measurement is ~126x.
    //
    // What IS true, and is the whole safety argument: the PREDICATE is org+supplier scoped on every
    // path, so the ROWS RETURNED are always one supplier's. The PAGES READ are not bounded by that
    // partition — a seq scan reads the table. This is a cost statement, not a tenancy one; tenancy
    // is enforced by the WHERE clause and covered by ItemMappingCaseParityTests.
    //
    // The accepted cost, stated plainly: sub-millisecond today, low single-digit milliseconds at a
    // few thousand mappings, once per order (the batch resolver issues ONE query for every line —
    // that is what keeps it bounded, not the index).
    //
    // No functional index / migration is added here on purpose:
    //   CREATE INDEX CONCURRENTLY ix_item_mappings_org_supplier_lower_code
    //       ON item_mappings (org_id, supplier_id, lower(buyer_item_code));
    // is DDL on a live production table and is the founder's call, not this change's. The artefact
    // is what that decision should be made on.

    /// <inheritdoc/>
    public async Task<string?> ResolveAsync(
        Guid orgId, Guid supplierId, string buyerItemCode, CancellationToken ct)
    {
        var trimmed = buyerItemCode.Trim();
        var key     = ItemCodeComparison.Key(trimmed);

        var candidates = await _db.ItemMappings
            .AsNoTracking()
            .Where(m => m.OrgId == orgId
                     && m.SupplierId == supplierId
                     && (m.BuyerItemCode == trimmed || m.BuyerItemCode.ToLower() == key))
            .Select(m => new MappingCandidate(m.Id, m.BuyerItemCode, m.SupplierItemCode, m.UpdatedAt))
            .ToListAsync(ct);

        return PickDeterministically(candidates, trimmed)?.SupplierItemCode;
    }

    /// <inheritdoc/>
    public async Task<IReadOnlyDictionary<string, string?>> ResolveManyAsync(
        Guid orgId, Guid supplierId, IEnumerable<string> buyerItemCodes, CancellationToken ct)
    {
        // ── Where the case rule does and does NOT belong ─────────────────────────────────────
        // Case-insensitivity belongs in the MATCH ("which stored row does this code find?"), never
        // in the RESULT KEYING ("which answer does this line get?").
        //
        // De-duplicating the requested codes case-INSENSITIVELY looks like a harmless optimisation
        // — one lookup instead of two — but it silently discards a code the caller asked about. For
        // an org that treats "B-1" and "b-1" as different products, the dictionary then answers the
        // "b-1" line from the "B-1" row and OrderIngestionService writes that supplier code onto the
        // line: the WRONG ITEM is ordered, with full confidence and no review flag. Pinned by
        // ItemMappingCaseParityTests.ResolveMany_WithTwoCaseVariantsOnOneOrder_AnswersEachLineSeparately.
        //
        // So: Ordinal here, and the folding happens below, per requested code, against the fetched
        // rows — which is also where ResolveAsync does it, so the two cannot disagree.
        var requested = buyerItemCodes
            .Where(c => !string.IsNullOrWhiteSpace(c))
            .Select(c => c.Trim())
            .Distinct(StringComparer.Ordinal)
            .ToList();

        // Seed every requested code with null so callers can treat the dictionary as total over the
        // (non-blank) input set — a missing key never throws.
        var result = new Dictionary<string, string?>(requested.Count, StringComparer.Ordinal);
        foreach (var code in requested)
            result[code] = null;

        if (requested.Count == 0)
            return result;

        var keys = requested.Select(ItemCodeComparison.Key).ToList();

        // One org+supplier-scoped query for all codes instead of N point lookups.
        var rows = await _db.ItemMappings
            .AsNoTracking()
            .Where(m => m.OrgId == orgId
                     && m.SupplierId == supplierId
                     && (requested.Contains(m.BuyerItemCode) || keys.Contains(m.BuyerItemCode.ToLower())))
            .Select(m => new MappingCandidate(m.Id, m.BuyerItemCode, m.SupplierItemCode, m.UpdatedAt))
            .ToListAsync(ct);

        // Resolve per REQUESTED code (not per row) so the same tie-break as ResolveAsync applies and
        // the two resolvers cannot disagree about which of two case-variant rows wins.
        foreach (var code in requested)
        {
            var matches = rows.Where(r => ItemCodeComparison.Matches(r.BuyerItemCode, code));
            result[code] = PickDeterministically(matches, code)?.SupplierItemCode;
        }

        return result;
    }

    /// <summary>
    /// THE shared existing-row rule for every WRITE path (<see cref="UpsertAsync"/>,
    /// <see cref="CreateAsync"/>, <see cref="UpdateByIdAsync"/> and the bulk CSV import, which
    /// reaches the database through them).
    ///
    /// <para>The WRITE side must use the SAME case rule as the read side. Fixing resolution alone is
    /// a trap: with a case-blind resolver but a case-SENSITIVE existing-row lookup, an operator
    /// correcting "b-1" while "B-1" is already stored inserts a SECOND row — the unique index
    /// IX(org_id, supplier_id, buyer_item_code) is case-SENSITIVE on Postgres's default collation,
    /// so the database happily permits it — and the resolver then has two candidates for one code.
    /// That converts a missed mapping into an unstable one, which is worse.</para>
    ///
    /// <para>Every write path calls THIS method rather than writing its own predicate. Three paths
    /// with three predicates is exactly how the read side and the catalog drifted apart in the first
    /// place; a fourth caller that hand-rolls the query is caught by
    /// <c>ItemCodeComparerGuardTests</c>.</para>
    ///
    /// <para>Tracked (not <c>AsNoTracking</c>) — callers mutate what comes back.</para>
    /// </summary>
    private async Task<ItemMapping?> FindExistingAsync(
        Guid orgId, Guid supplierId, string normalisedCode, CancellationToken ct)
    {
        var key = ItemCodeComparison.Key(normalisedCode);

        var candidates = await _db.ItemMappings
            .Where(m => m.OrgId == orgId
                     && m.SupplierId == supplierId
                     && (m.BuyerItemCode == normalisedCode || m.BuyerItemCode.ToLower() == key))
            .ToListAsync(ct);

        if (candidates.Count == 0) return null;

        // Same precedence as PickDeterministically: an exact-case row wins, then most-recently
        // updated, then id. Stated once here so the write side cannot pick a different twin from the
        // one the resolver will read back.
        return candidates.FirstOrDefault(
                   m => string.Equals(m.BuyerItemCode, normalisedCode, StringComparison.Ordinal))
               ?? candidates.OrderByDescending(m => m.UpdatedAt).ThenBy(m => m.Id).First();
    }

    /// <inheritdoc/>
    public async Task UpsertAsync(
        Guid orgId, Guid supplierId,
        string buyerItemCode, string supplierItemCode,
        MappingSource source, float? confidence, CancellationToken ct)
    {
        var normalised = buyerItemCode.Trim();
        var sourceStr  = source.ToString().ToLowerInvariant();

        // Matching case-insensitively here means a correction always UPDATES the mapping it corrects.
        var existing = await FindExistingAsync(orgId, supplierId, normalised, ct);

        var now = DateTime.UtcNow;

        if (existing is null)
        {
            _db.ItemMappings.Add(new ItemMapping
            {
                Id               = Guid.NewGuid(),
                OrgId            = orgId,
                SupplierId       = supplierId,
                BuyerItemCode    = normalised,
                SupplierItemCode = supplierItemCode.Trim(),
                // Whatever the caller measured, or null. This was
                // `source == MappingSource.Manual ? 1.0f : 0.8f` — a two-valued literal under a
                // column the supplier screen heads "Confidence", so a hand-typed code claimed a
                // green 100% and an imported one a flat amber 80%, neither of them measured.
                Confidence       = confidence,
                Source           = sourceStr,
                AppliedCount     = 1,
                CreatedAt        = now,
                UpdatedAt        = now
            });
        }
        else
        {
            var codeChanged = !string.Equals(
                existing.SupplierItemCode, supplierItemCode.Trim(),
                StringComparison.OrdinalIgnoreCase);

            if (codeChanged)
            {
                _db.MappingCorrections.Add(new MappingCorrection
                {
                    Id                  = Guid.NewGuid(),
                    OrgId               = orgId,
                    MappingId           = existing.Id,
                    OldSupplierItemCode = existing.SupplierItemCode,
                    NewSupplierItemCode = supplierItemCode.Trim(),
                    Source              = sourceStr,
                    CorrectedAt         = now,
                });
            }

            existing.SupplierItemCode = supplierItemCode.Trim();
            existing.Source           = sourceStr;
            // A re-save carrying a real score overwrites; a re-save carrying none (hand-typed,
            // imported) CLEARS, because the stored number no longer describes the code now held.
            // Keeping the old score here would let a 0.91 from a previous accept sit against a
            // code a human has since typed over the top of it.
            existing.Confidence       = confidence;
            existing.AppliedCount    += 1;
            existing.UpdatedAt        = now;
        }

        await _db.SaveChangesAsync(ct);
    }

    /// <inheritdoc/>
    public async Task<IReadOnlyList<ItemMapping>> GetForSupplierAsync(
        Guid orgId, Guid supplierId, CancellationToken ct)
    {
        return await _db.ItemMappings
            .AsNoTracking()
            .Where(m => m.OrgId == orgId && m.SupplierId == supplierId)
            .OrderBy(m => m.BuyerItemCode)
            .ToListAsync(ct);
    }

    /// <inheritdoc/>
    public async Task DeleteAsync(Guid orgId, Guid mappingId, CancellationToken ct)
    {
        var mapping = await _db.ItemMappings
            .Where(m => m.Id == mappingId && m.OrgId == orgId)
            .FirstOrDefaultAsync(ct);

        if (mapping is not null)
        {
            _db.ItemMappings.Remove(mapping);
            await _db.SaveChangesAsync(ct);
        }
    }

    /// <inheritdoc/>
    public async Task<ItemMapping> CreateAsync(
        Guid orgId, Guid supplierId,
        string buyerItemCode, string supplierItemCode,
        MappingSource source, float? confidence, CancellationToken ct)
    {
        var normalised = buyerItemCode.Trim();

        // This used to be a blind insert with NO existence check — reached from POST
        // /api/suppliers/{id}/mappings AND from the bulk CSV import, so it created exactly the
        // case-variant twin UpsertAsync's contract says must never exist. Routed through the shared
        // rule: an operator typing "b-1" when "B-1" is already mapped means "correct that mapping",
        // not "make a second one nothing can deterministically choose between".
        var existing = await FindExistingAsync(orgId, supplierId, normalised, ct);
        var now      = DateTime.UtcNow;

        if (existing is not null)
        {
            existing.SupplierItemCode = supplierItemCode.Trim();
            existing.Source           = source.ToString().ToLowerInvariant();
            existing.Confidence       = confidence; // see UpsertAsync — null clears, it does not preserve
            existing.UpdatedAt        = now;
            await _db.SaveChangesAsync(ct);
            return existing;
        }

        var mapping = new ItemMapping
        {
            Id               = Guid.NewGuid(),
            OrgId            = orgId,
            SupplierId       = supplierId,
            BuyerItemCode    = normalised,
            SupplierItemCode = supplierItemCode.Trim(),
            Confidence       = confidence, // see UpsertAsync — was `Manual ? 1.0f : 0.8f`
            Source           = source.ToString().ToLowerInvariant(),
            CreatedAt        = now,
            UpdatedAt        = now,
        };
        _db.ItemMappings.Add(mapping);
        await _db.SaveChangesAsync(ct);
        return mapping;
    }

    /// <inheritdoc/>
    public async Task<ItemMapping?> UpdateByIdAsync(
        Guid orgId, Guid mappingId,
        string buyerItemCode, string supplierItemCode,
        MappingSource source, CancellationToken ct)
    {
        var mapping = await _db.ItemMappings
            .Where(m => m.Id == mappingId && m.OrgId == orgId)
            .FirstOrDefaultAsync(ct);
        if (mapping is null) return null;

        var normalised = buyerItemCode.Trim();

        // Renaming this mapping onto a spelling ANOTHER row already owns would create the twin.
        // The three options are: allow it (two rows, unstable resolution — the defect), merge them
        // (DELETES a row the operator did not ask to delete — a founder decision about their data,
        // not this method's), or refuse. Refuse is the only one that neither corrupts nor destroys;
        // the caller turns the null into a 409 so the operator is told, not silently ignored.
        // Re-casing a mapping's OWN code is a normal edit and stays allowed.
        var collision = await FindExistingAsync(orgId, mapping.SupplierId, normalised, ct);
        if (collision is not null && collision.Id != mapping.Id) return null;

        mapping.BuyerItemCode    = normalised;
        mapping.SupplierItemCode = supplierItemCode.Trim();
        mapping.Source           = source.ToString().ToLowerInvariant();
        // An operator retyping this mapping's codes through the editor. Nothing scored the result,
        // so it carries no score — this used to stamp a literal 1.0f, which is how a row an
        // operator had just hand-corrected came to display a green "100% confidence".
        mapping.Confidence       = null;
        mapping.UpdatedAt        = DateTime.UtcNow;
        await _db.SaveChangesAsync(ct);
        return mapping;
    }

    /// <inheritdoc/>
    public async Task<IReadOnlyList<ItemCodeTwinGroup>> FindCaseVariantTwinsAsync(
        Guid orgId, CancellationToken ct)
    {
        // DETECTION ONLY. This reports the twins production already holds; it never merges or
        // deletes one. Which spelling survives a merge is a decision about a customer's data and
        // belongs to the founder, not to a background job — and the resolver is deterministic in
        // the meantime (exact-case wins, then UpdatedAt DESC, then Id), so nothing is unstable while
        // the decision is pending.
        //
        // Grouped in SQL by (org_id, supplier_id, lower(buyer_item_code)) so the whole org is one
        // query. Org-scoped like every other read here.
        var groups = await _db.ItemMappings
            .AsNoTracking()
            .Where(m => m.OrgId == orgId)
            .GroupBy(m => new { m.SupplierId, Folded = m.BuyerItemCode.ToLower() })
            .Where(g => g.Count() > 1)
            .Select(g => new
            {
                g.Key.SupplierId,
                g.Key.Folded,
                Count     = g.Count(),
                Spellings = g.Select(m => m.BuyerItemCode).ToList(),
            })
            .ToListAsync(ct);

        return groups
            .OrderBy(g => g.SupplierId)
            .ThenBy(g => g.Folded, StringComparer.Ordinal)
            .Select(g => new ItemCodeTwinGroup(
                g.SupplierId,
                g.Folded,
                g.Count,
                g.Spellings.OrderBy(s => s, StringComparer.Ordinal).ToList()))
            .ToList();
    }
}
