// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProcuLink.Infrastructure;

#nullable disable

namespace ProcuLink.Infrastructure.Migrations
{
    [DbContext(typeof(ProcuLinkDbContext))]
    [Migration("20260524204258_AddSupplierPoMappings")]
    partial class AddSupplierPoMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProcuLink.Core.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clerk_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("UserId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("attempted_at");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrgId");

                    b.ToTable("delivery_attempts", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.ItemMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuyerItemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("buyer_item_code");

                    b.Property<float>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierItemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_item_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("OrgId", "SupplierId", "BuyerItemCode")
                        .IsUnique();

                    b.ToTable("item_mappings", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("UserId");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClerkOrgId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clerk_org_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PilotExtendedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("pilot_extended_until");

                    b.Property<DateTime?>("PilotExtensionRequestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("pilot_extension_requested_at");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTime>("TrialStartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("trial_started_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ClerkOrgId")
                        .IsUnique();

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.OutboundArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_key");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrgId");

                    b.ToTable("outbound_artifacts", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.PurchaseOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("CanonicalJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("canonical_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("po_number");

                    b.Property<string>("SourceFileKey")
                        .HasColumnType("text")
                        .HasColumnName("source_file_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("SupplierId");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.PurchaseOrderLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuyerItemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("buyer_item_code");

                    b.Property<float>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_review");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("SupplierItemCode")
                        .HasColumnType("text")
                        .HasColumnName("supplier_item_code");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("purchase_order_lines", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.SupplierPoMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("OrgId", "SupplierId")
                        .IsUnique();

                    b.ToTable("supplier_po_mappings", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.SupplierProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<string>>("AcceptedFormats")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("accepted_formats");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("DestinationConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("destination_config");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_type");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("output_format");

                    b.Property<JsonDocument>("RequiredFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("required_fields");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("SupplierId");

                    b.ToTable("supplier_profiles", (string)null);
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.AuditEvent", b =>
                {
                    b.HasOne("ProcuLink.Core.Entities.Organisation", "Organisation")
                        .WithMany("AuditEvents")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcuLink.Core.Entities.AppUser", "User")
                        .WithMany("AuditEvents")
                        .HasForeignKey("UserId");

                    b.Navigation("Organisation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.DeliveryAttempt", b =>
                {
                    b.HasOne("ProcuLink.Core.Entities.PurchaseOrderEntity", "Order")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcuLink.Core.Entities.Organisation", "Organisation")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.ItemMapping", b =>
                {
                    b.HasOne("ProcuLink.Core.Entities.Organisation", "Organisation")
                        .WithMany("ItemMappings")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcuLink.Core.Entities.Supplier", "Supplier")
                        .WithMany("ItemMappings")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.Membership", b =>
                {
                    b.HasOne("ProcuLink.Core.Entities.Organisation", "Organisation")
                        .WithMany("Memberships")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcuLink.Core.Entities.AppUser", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.OutboundArtifact", b =>
                {
                    b.HasOne("ProcuLink.Core.Entities.PurchaseOrderEntity", "Order")
                        .WithMany("OutboundArtifacts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcuLink.Core.Entities.Organisation", "Organisation")
                        .WithMany("OutboundArtifacts")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.PurchaseOrderEntity", b =>
                {
                    b.HasOne("ProcuLink.Core.Entities.Organisation", "Organisation")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcuLink.Core.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.PurchaseOrderLineEntity", b =>
                {
                    b.HasOne("ProcuLink.Core.Entities.PurchaseOrderEntity", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.Supplier", b =>
                {
                    b.HasOne("ProcuLink.Core.Entities.Organisation", "Organisation")
                        .WithMany("Suppliers")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.SupplierPoMapping", b =>
                {
                    b.HasOne("ProcuLink.Core.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcuLink.Core.Entities.Supplier", "Supplier")
                        .WithMany("PoMappings")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.SupplierProfileEntity", b =>
                {
                    b.HasOne("ProcuLink.Core.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcuLink.Core.Entities.Supplier", "Supplier")
                        .WithMany("SupplierProfiles")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.AppUser", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.Organisation", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("DeliveryAttempts");

                    b.Navigation("ItemMappings");

                    b.Navigation("Memberships");

                    b.Navigation("OutboundArtifacts");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.PurchaseOrderEntity", b =>
                {
                    b.Navigation("DeliveryAttempts");

                    b.Navigation("Lines");

                    b.Navigation("OutboundArtifacts");
                });

            modelBuilder.Entity("ProcuLink.Core.Entities.Supplier", b =>
                {
                    b.Navigation("ItemMappings");

                    b.Navigation("PoMappings");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("SupplierProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
